/**
 * Generates runtime connection modules + TypeScript declarations from cached MCP schemas.
 * Run after `jig connect <server>` to make tools available in jigs.
 *
 * Produces:
 *   .jig/types/{server}.d.ts   — type declarations (IDE autocomplete)
 *   .jig/connections/{server}.ts — runtime module (actual MCP calls)
 *   .jig/connections/index.ts   — barrel export of all connected servers
 *
 * Usage: bun run src/mcp/typegen.ts
 */
import { join } from "node:path"
import { readdir, mkdir } from "node:fs/promises"
import type { Tool } from "@modelcontextprotocol/sdk/types.js"
import { CONNECTIONS_DIR, PROJECT_ROOT, SCHEMAS_DIR, TYPES_DIR } from "../config/paths.js"
import { firstLineSummary } from "../text.js"

const JS_RESERVED_WORDS = new Set([
  "break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete",
  "do", "else", "export", "extends", "finally", "for", "function", "if", "import", "in",
  "instanceof", "new", "return", "super", "switch", "this", "throw", "try", "typeof",
  "var", "void", "while", "with", "yield", "enum", "await", "implements", "package",
  "protected", "static", "interface", "private", "public", "let",
])

function isSafeIdentifier(name: string): boolean {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) && !JS_RESERVED_WORDS.has(name)
}

export function toolNameToIdentifier(name: string): string {
  const normalized = name
    .replace(/[^A-Za-z0-9_$]+/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_+|_+$/g, "")
  const base = normalized || "tool"
  const prefixed = /^[A-Za-z_$]/.test(base) ? base : `_${base}`
  return JS_RESERVED_WORDS.has(prefixed) ? `_${prefixed}` : prefixed
}

function renderTsPropertyName(name: string): string {
  return isSafeIdentifier(name) ? name : JSON.stringify(name)
}

function jsonSchemaTypeToTS(prop: any): string {
  if (prop.enum) {
    return prop.enum.map((v: string) => `"${v}"`).join(" | ")
  }

  switch (prop.type) {
    case "string":
      return "string"
    case "number":
    case "integer":
      return "number"
    case "boolean":
      return "boolean"
    case "array":
      if (prop.items?.type === "string") return "string[]"
      if (prop.items?.type === "number" || prop.items?.type === "integer") return "number[]"
      return "unknown[]"
    case "object":
      return "Record<string, unknown>"
    default:
      return "unknown"
  }
}

function generateToolParams(tool: Tool): string {
  const schema = tool.inputSchema as any
  if (!schema?.properties || Object.keys(schema.properties).length === 0) {
    return "{}"
  }

  const requiredSet = new Set<string>(schema.required ?? [])
  const lines: string[] = []

  for (const [name, prop] of Object.entries(schema.properties) as [string, any][]) {
    const isRequired = requiredSet.has(name)
    const tsType = jsonSchemaTypeToTS(prop)
    const desc = prop.description ? ` /** ${prop.description.replace(/\*\//g, "* /")} */\n    ` : ""
    const opt = isRequired ? "" : "?"
    lines.push(`${desc}${renderTsPropertyName(name)}${opt}: ${tsType}`)
  }

  return `{ ${lines.join("; ")} }`
}

export function generateTypeDeclaration(serverName: string, tools: Tool[]): string {
  const lines: string[] = [
    `// Auto-generated by jig typegen — do not edit`,
    `import type { JigTool } from "../../src/sdk/jig"`,
    ``,
    `export declare const ${serverName}: {`,
  ]

  for (const tool of tools) {
    const desc = firstLineSummary(tool.description).replace(/\*\//g, "* /")
    const params = generateToolParams(tool)
    const identifier = toolNameToIdentifier(tool.name)
    lines.push(`  /** ${desc} */`)
    lines.push(`  ${identifier}: JigTool<${params}, unknown>`)
    lines.push(``)
  }

  lines.push(`}`)
  return lines.join("\n")
}

export function generateRuntimeModule(serverName: string, tools: Tool[]): string {
  const readOnlySet = new Set(tools.filter(t => (t as any).annotations?.readOnlyHint).map(t => t.name))
  const toolLines = tools.map(t =>
    `export const ${toolNameToIdentifier(t.name)} = tool("${t.name}", ${readOnlySet.has(t.name)})`
  )
  const objectEntries = tools.flatMap((tool) => {
    const identifier = toolNameToIdentifier(tool.name)
    return identifier === tool.name
      ? [identifier]
      : [`${identifier}`, `${JSON.stringify(tool.name)}: ${identifier}`]
  })

  return `// Auto-generated by jig typegen — do not edit
import { getServerConfig } from "../../src/mcp/config"
import { connectServer, callTool, registerConnection, shouldReconnectMcpConnection } from "../../src/mcp/client"
import { buildDryRunToolResult, isDryRun, shouldStubToolInDryRun } from "../../src/sdk/dryrun"
import { runContext } from "../../src/sdk/context"
import type { JigTool } from "../../src/sdk/jig"

let _pending: Promise<any> | null = null
async function conn() {
  if (!_pending) {
    _pending = (async () => {
      const cfg = await getServerConfig("${serverName}")
      const c = await connectServer("${serverName}", cfg)
      registerConnection("${serverName}", c)
      return c
    })()
  }
  return _pending
}

export async function closeConnection() {
  if (_pending) {
    try {
      const c = await _pending
      await c.transport.close().catch(() => {})
      await c.client.close().catch(() => {})
    } catch {}
    _pending = null
  }
}

async function invokeWithReconnect<T>(run: () => Promise<T>): Promise<T> {
  try {
    return await run()
  } catch (error) {
    if (!shouldReconnectMcpConnection(error)) throw error
    await closeConnection()
    return run()
  }
}

function tool(name: string, readOnly: boolean) {
  const fn = async (params: any) => {
    const ctx = runContext.getStore()
    if (ctx && !ctx.isToolAllowedInCurrentStep(name)) {
      throw new Error(
        \`Tool "${serverName}.\${name}" is not allowed in step "\${ctx.currentStepLabel ?? "(no active step)"}". \`
        + \`Declare it in the tools array of your ctx.step() call.\`
      )
    }
    if (isDryRun() && !readOnly) {
      ctx?.output(\`[dry-run] Would call ${serverName}.\${name} with \${JSON.stringify(params ?? {})}\`)
      return buildDryRunToolResult(name, params ?? {}, readOnly)
    }
    if (isDryRun() && readOnly && shouldStubToolInDryRun(params)) {
      ctx?.output(\`[dry-run] Skipping ${serverName}.\${name} because its params depend on a skipped tool result\`)
      return buildDryRunToolResult(name, params ?? {}, readOnly)
    }
    return invokeWithReconnect(async () => callTool(await conn(), name, params ?? {}))
  }
  fn._serverName = "${serverName}"
  fn._toolName = name
  fn._readOnly = readOnly
  return fn as JigTool<any, any>
}

${toolLines.join("\n")}

export const ${serverName} = { ${objectEntries.join(", ")} }
`
}

export function generateProxyRuntimeModule(serverName: string, tools: Tool[], proxyCallCode: string): string {
  const readOnlySet = new Set(tools.filter(t => (t as any).annotations?.readOnlyHint).map(t => t.name))
  const toolLines = tools.map(t =>
    `export const ${toolNameToIdentifier(t.name)} = tool("${t.name}", ${readOnlySet.has(t.name)})`
  )
  const objectEntries = tools.flatMap((tool) => {
    const identifier = toolNameToIdentifier(tool.name)
    return identifier === tool.name
      ? [identifier]
      : [`${identifier}`, `${JSON.stringify(tool.name)}: ${identifier}`]
  })

  return `// Auto-generated by jig typegen — do not edit (proxy module)
import { getServerConfig } from "../../src/mcp/config"
import { connectServer, callTool, registerConnection, shouldReconnectMcpConnection } from "../../src/mcp/client"
import { buildDryRunToolResult, isDryRun, shouldStubToolInDryRun } from "../../src/sdk/dryrun"
import { runContext } from "../../src/sdk/context"
import type { JigTool } from "../../src/sdk/jig"

let _pending: Promise<any> | null = null
async function conn() {
  if (!_pending) {
    _pending = (async () => {
      const cfg = await getServerConfig("${serverName}")
      const c = await connectServer("${serverName}", cfg)
      registerConnection("${serverName}", c)
      return c
    })()
  }
  return _pending
}

export async function closeConnection() {
  if (_pending) {
    try {
      const c = await _pending
      await c.transport.close().catch(() => {})
      await c.client.close().catch(() => {})
    } catch {}
    _pending = null
  }
}

async function invokeWithReconnect<T>(run: () => Promise<T>): Promise<T> {
  try {
    return await run()
  } catch (error) {
    if (!shouldReconnectMcpConnection(error)) throw error
    await closeConnection()
    return run()
  }
}

function tool(name: string, readOnly: boolean) {
  const fn = async (params: any) => {
    const ctx = runContext.getStore()
    if (ctx && !ctx.isToolAllowedInCurrentStep(name)) {
      throw new Error(
        \`Tool "${serverName}.\${name}" is not allowed in step "\${ctx.currentStepLabel ?? "(no active step)"}". \`
        + \`Declare it in the tools array of your ctx.step() call.\`
      )
    }
    if (isDryRun() && !readOnly) {
      ctx?.output(\`[dry-run] Would call ${serverName}.\${name} with \${JSON.stringify(params ?? {})}\`)
      return buildDryRunToolResult(name, params ?? {}, readOnly)
    }
    if (isDryRun() && readOnly && shouldStubToolInDryRun(params)) {
      ctx?.output(\`[dry-run] Skipping ${serverName}.\${name} because its params depend on a skipped tool result\`)
      return buildDryRunToolResult(name, params ?? {}, readOnly)
    }
    return invokeWithReconnect(async () => {
${proxyCallCode}
    })
  }
  fn._serverName = "${serverName}"
  fn._toolName = name
  fn._readOnly = readOnly
  return fn as JigTool<any, any>
}

${toolLines.join("\n")}

export const ${serverName} = { ${objectEntries.join(", ")} }
`
}

export async function generateConnectionArtifacts() {
  const { loadServerConfigs } = await import("./config.js")
  const serverConfigs = await loadServerConfigs()

  const files = await readdir(SCHEMAS_DIR).catch(() => [] as string[])
  const schemaFiles = files.filter((f) => f.endsWith(".json"))

  if (schemaFiles.length === 0) {
    console.log("[typegen] No schemas found in .jig/schemas/. Connect a server first.")
    return
  }

  await mkdir(TYPES_DIR, { recursive: true })
  await mkdir(CONNECTIONS_DIR, { recursive: true })

  const servers: string[] = []

  for (const file of schemaFiles) {
    const serverName = file.replace(".json", "")
    const tools: Tool[] = await Bun.file(join(SCHEMAS_DIR, file)).json()

    // Type declaration (same for proxy and direct)
    const typesContent = generateTypeDeclaration(serverName, tools)
    await Bun.write(join(TYPES_DIR, `${serverName}.d.ts`), typesContent)

    // Runtime connection module — proxy or direct
    const cfg = serverConfigs[serverName]
    let runtimeContent: string
    if (cfg?.proxy?.connectDiscovery) {
      const { proxyCallCode } = await import(join(PROJECT_ROOT, cfg.proxy.connectDiscovery))
      runtimeContent = generateProxyRuntimeModule(serverName, tools, proxyCallCode)
    } else {
      runtimeContent = generateRuntimeModule(serverName, tools)
    }
    await Bun.write(join(CONNECTIONS_DIR, `${serverName}.ts`), runtimeContent)

    servers.push(serverName)
    console.log(`[typegen] ${serverName}: ${tools.length} tools${cfg?.proxy ? " (proxy)" : ""}`)
  }

  // Barrel exports
  const barrelExports = servers
    .map((s) => `export { ${s} } from "./${s}"`)
    .join("\n")

  await Bun.write(
    join(TYPES_DIR, "index.d.ts"),
    `// Auto-generated by jig typegen — do not edit\n${barrelExports}\n`
  )

  await Bun.write(
    join(CONNECTIONS_DIR, "index.ts"),
    `// Auto-generated by jig typegen — do not edit\n${barrelExports}\n`
  )

  // Derive notification-capable-tools manifest from annotated schemas
  const { buildNotificationManifest } = await import("./discover/notification-manifest.js")
  const manifest = buildNotificationManifest()
  if (manifest.length > 0) {
    console.log(`[typegen] notification manifest: ${manifest.length} tool(s) — ${manifest.map(m => m.label).join(", ")}`)
  }

  console.log(`[typegen] Done. ${servers.length} server(s) ready.`)
}

async function main() {
  await generateConnectionArtifacts()
}

// Only run main() when executed directly, not when imported for testing
if (import.meta.main) {
  main()
}
