/**
 * Generates runtime connection modules + TypeScript declarations from cached MCP schemas.
 * Run after `jig connect <server>` to make tools available in jigs.
 *
 * Produces:
 *   .jig/types/{server}.d.ts   — type declarations (IDE autocomplete)
 *   .jig/connections/{server}.ts — runtime module (actual MCP calls)
 *   .jig/connections/index.ts   — barrel export of all connected servers
 *
 * Usage: bun run src/mcp/typegen.ts
 */
import { join } from "node:path"
import { readdir, mkdir } from "node:fs/promises"
import type { Tool } from "@modelcontextprotocol/sdk/types.js"
import { CONNECTIONS_DIR, PROJECT_ROOT, SCHEMAS_DIR, TYPES_DIR } from "../config/paths.js"

function jsonSchemaTypeToTS(prop: any): string {
  if (prop.enum) {
    return prop.enum.map((v: string) => `"${v}"`).join(" | ")
  }

  switch (prop.type) {
    case "string":
      return "string"
    case "number":
    case "integer":
      return "number"
    case "boolean":
      return "boolean"
    case "array":
      if (prop.items?.type === "string") return "string[]"
      if (prop.items?.type === "number" || prop.items?.type === "integer") return "number[]"
      return "unknown[]"
    case "object":
      return "Record<string, unknown>"
    default:
      return "unknown"
  }
}

function generateToolParams(tool: Tool): string {
  const schema = tool.inputSchema as any
  if (!schema?.properties || Object.keys(schema.properties).length === 0) {
    return "{}"
  }

  const requiredSet = new Set<string>(schema.required ?? [])
  const lines: string[] = []

  for (const [name, prop] of Object.entries(schema.properties) as [string, any][]) {
    const isRequired = requiredSet.has(name)
    const tsType = jsonSchemaTypeToTS(prop)
    const desc = prop.description ? ` /** ${prop.description} */\n    ` : ""
    const opt = isRequired ? "" : "?"
    lines.push(`${desc}${name}${opt}: ${tsType}`)
  }

  return `{ ${lines.join("; ")} }`
}

function generateTypeDeclaration(serverName: string, tools: Tool[]): string {
  const lines: string[] = [
    `// Auto-generated by jig typegen — do not edit`,
    `import type { JigTool } from "../../src/sdk/jig"`,
    ``,
    `export declare const ${serverName}: {`,
  ]

  for (const tool of tools) {
    const desc = tool.description?.split("\n")[0] ?? ""
    const params = generateToolParams(tool)
    lines.push(`  /** ${desc} */`)
    lines.push(`  ${tool.name}: JigTool<${params}, unknown>`)
    lines.push(``)
  }

  lines.push(`}`)
  return lines.join("\n")
}

function generateRuntimeModule(serverName: string, tools: Tool[]): string {
  const readOnlySet = new Set(tools.filter(t => (t as any).annotations?.readOnlyHint).map(t => t.name))
  const toolLines = tools.map(t =>
    `export const ${t.name} = tool("${t.name}", ${readOnlySet.has(t.name)})`
  )

  return `// Auto-generated by jig typegen — do not edit
import { getServerConfig } from "../../src/mcp/config"
import { connectServer, callTool, registerConnection } from "../../src/mcp/client"
import { isDryRun } from "../../src/sdk/dryrun"
import { runContext, isStepScan } from "../../src/sdk/context"
import type { JigTool } from "../../src/sdk/jig"

let _pending: Promise<any> | null = null
async function conn() {
  if (!_pending) {
    _pending = (async () => {
      const cfg = await getServerConfig("${serverName}")
      const c = await connectServer("${serverName}", cfg)
      registerConnection("${serverName}", c)
      return c
    })()
  }
  return _pending
}

export async function closeConnection() {
  if (_pending) {
    try {
      const c = await _pending
      await c.transport.close().catch(() => {})
      await c.client.close().catch(() => {})
    } catch {}
    _pending = null
  }
}

function tool(name: string, readOnly: boolean) {
  const fn = async (params: any) => {
    const ctx = runContext.getStore()
    if (ctx && !ctx.inAgent) ctx.step("${serverName}." + name)
    ctx?.addConnection("${serverName}")
    if (isStepScan()) return {} as any
    if (isDryRun() && !readOnly) {
      console.log(\`\\n[dry-run] ${serverName}.\${name}\`)
      return { _dryRun: true, tool: name, params }
    }
    return callTool(await conn(), name, params ?? {})
  }
  fn._serverName = "${serverName}"
  fn._toolName = name
  fn._readOnly = readOnly
  return fn as JigTool<any, any>
}

${toolLines.join("\n")}

export const ${serverName} = { ${tools.map(t => t.name).join(", ")} }
`
}

async function main() {
  const files = await readdir(SCHEMAS_DIR).catch(() => [] as string[])
  const schemaFiles = files.filter((f) => f.endsWith(".json"))

  if (schemaFiles.length === 0) {
    console.log("[typegen] No schemas found in .jig/schemas/. Connect a server first.")
    return
  }

  await mkdir(TYPES_DIR, { recursive: true })
  await mkdir(CONNECTIONS_DIR, { recursive: true })

  const servers: string[] = []

  for (const file of schemaFiles) {
    const serverName = file.replace(".json", "")
    const tools: Tool[] = await Bun.file(join(SCHEMAS_DIR, file)).json()

    // Type declaration
    const typesContent = generateTypeDeclaration(serverName, tools)
    await Bun.write(join(TYPES_DIR, `${serverName}.d.ts`), typesContent)

    // Runtime connection module
    const runtimeContent = generateRuntimeModule(serverName, tools)
    await Bun.write(join(CONNECTIONS_DIR, `${serverName}.ts`), runtimeContent)

    servers.push(serverName)
    console.log(`[typegen] ${serverName}: ${tools.length} tools`)
  }

  // Barrel exports
  const barrelExports = servers
    .map((s) => `export { ${s} } from "./${s}"`)
    .join("\n")

  await Bun.write(
    join(TYPES_DIR, "index.d.ts"),
    `// Auto-generated by jig typegen — do not edit\n${barrelExports}\n`
  )

  await Bun.write(
    join(CONNECTIONS_DIR, "index.ts"),
    `// Auto-generated by jig typegen — do not edit\n${barrelExports}\n`
  )

  console.log(`[typegen] Done. ${servers.length} server(s) ready.`)
}

main()
